# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

# Orchestrate or schedule a set of jobs
jobs:
  build-and-test:
      docker:
        - image: circleci/python:3.8
      steps:
        - checkout
        - run:
            command: pip install -e .
            name: Install Deps
        - run:
            command: |
              export PATH=$PATH:$PWD
              pytest tests/
            name: Test
        - run:
            command: |
              $HOME/.local/bin/coverage run -m pytest
              $HOME/.local/bin/coverage report
              $HOME/.local/bin/coverage html
            name: Test Code Coverage
        - store_artifacts:
            path: htmlcov



workflows:
  # Name the workflow "test"
  test:
    # Run the welcome/run job in its own container
    jobs:
      - build-and-test
